---
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - "tests/**/*"
  - ".*"
  - "*.md"
  - "*.json"
  - "*.xml"
