language: php

php:
  - 5.6
  - 5.5
  - 7.0
  - hhvm

env:
  - LARAVEL=4.2
  - LARAVEL=5.0
  - LARAVEL=5.1
  - LARAVEL=dev-master

install:
  - php scripts/test-with-laravel.php $LARAVEL
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php vendor/bin/coveralls -v; fi;'